apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: ab
  labels:
    app: receiver-app
spec:
  selector:
    app: receiver-app
  ports:
  - protocol: TCP
    port: 8080
    name: http
    targetPort: 80
