apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-deployment
  namespace: ab
  labels:
    app: caller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-app
  template:
    metadata:
      labels:
        app: caller-app
    spec:
      containers:
      - name: callerapp
        image: nbabusundaram/caller:v1
        ports:
        - containerPort: 80
