apiVersion: v1
kind: Service
metadata:
  name: caller-service
  namespace: ab
  labels:
    app: caller-app
spec:
  selector:
    app: caller-app
  ports:
  - protocol: TCP
    port: 8080
    name: http
    targetPort: 80
