apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: ab
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: header-service
        image: nbabusundaram/header-service
        ports:
        - containerPort: 80
