apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: ab
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    name: http
    targetPort: 80
